name: Cookbook
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

nav_pages:
    - ind_geno_qc.md
    - phenotyping.md
    - pre_phasing_checks.md
    - gwas.md
    - post_gwas_checks.md
