title: Cookbook
remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes navigation
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Sidebar navigation
# Create a _data/navigation.yml file for custom sidebar