title: Cookbook
theme: "minimal-mistakes-jekyll"

# Minimal Mistakes navigation
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Sidebar navigation
# Create a _data/navigation.yml file for custom sidebar