name: Cookbook
theme: minima

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

minima:
  nav_pages:
    - ind_geno_qc.md
    - phenotyping.md
    - pre_phasing_checks.md
    - gwas.md
    - post_gwas_checks.md
